AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with full public access and website hosting

Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
    Default: circuitscan-artifacts

Resources:
  PrimaryS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - '*'
            MaxAge: 3000

  PrimaryBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PrimaryS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource:
              - !Sub 'arn:aws:s3:::${BucketName}/*'

Outputs:
  PrimaryWebsiteURL:
    Description: URL of the primary S3 bucket website endpoint
    Value: !GetAtt
      - PrimaryS3Bucket
      - WebsiteURL


