AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Lambda function from an ECR image with a function URL

Parameters:
  ECRRepoName:
    Type: String
    Description: The name of the ECR repository
    Default: circuitscan_server
  ECRImageTag:
    Type: String
    Description: The tag of the ECR image
    Default: latest
  AssocBucket:
    Type: String
    Description: S3 Bucket in which to store package/address associations
    Default: circuitscan-artifacts
  MaxNewest:
    Type: String
    Description: Maximum number of verifiers to keep in latest.json
    Default: 100
  BlobUrl:
    Type: String
    Description: Where compilation artifacts are stored
    Default: https://circuitscan-artifacts.s3.us-west-2.amazonaws.com/

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource:
                  - !Sub arn:aws:s3:::${AssocBucket}/*
                  - !Sub arn:aws:s3:::${AssocBucket}

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ECRRepoName}-lambda-function"
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepoName}:${ECRImageTag}"
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          ASSOC_BUCKET: !Ref AssocBucket
          MAX_NEWEST: !Ref MaxNewest
          BLOB_URL: !Ref BlobUrl

  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt LambdaFunction.Arn
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "*"
        AllowHeaders:
          - "*"

  LambdaFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunctionUrl"
      FunctionName: !Ref LambdaFunction
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  LambdaFunctionUrl:
    Description: The URL of the Lambda function
    Value: !GetAtt LambdaFunctionUrl.FunctionUrl

